name: CI

run-name: Running checks

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_call:

jobs:
  test:    
    name: Tests 
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "Ensure branch targets development"
        if: ${{ github.base_ref != 'development' }}
        run: exit 0
        
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Setup node"
        uses: actions/setup-node@v3
        with:
          node-version: 18.10

      - name: "Install"
        run: npm ci

      - name: "Unit test"
        run: npm run test:unit
