name: CI

run-name: Running checks

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_call:

jobs:
  test:
    name: Tests 
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Setup node"
        uses: actions/setup-node@v3
        with:
          node-version: 18.10

      - name: Get changed applications
        id: diff
        uses: tj-actions/changed-files@v36
        with:
          files: apps
          dir_names: true
          dir_names_exclude_current_dir: true
          json: true
          escape_json: true

      - name: Generate testing matrix
        uses: actions/github-script@v6
        id: generator
        with:
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/ci/generateBuildMatrix.js`)
            return script(
              ${{ steps.diff.outputs.added_files }},
              ${{ steps.diff.outputs.modified_files }},
              ${{ steps.diff.outputs.renamed_files }},
            );

      - name: "Install"
        run: npm ci

      - name: "Unit test"
        run: npm run test:unit
